### PR TITLE
fix: error handling (#19)

### LINKED ISSUE #19: Error handling for when people leaving

### PR DESCRIPTION
**Pull request by eddiejaoude**
closes #19 

- [x] if people leave the bot crashes

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBotBreakout/pull/20"></a>

### CODE REVIEW

File: src/modules/subcommands/handleBreakout.ts [hunk 1]
```diff
@@ -20,13 +21,23 @@ export const handleBreakout: CommandHandler = async (bot, interaction) => {
     return;
   }
 
+  if (interaction.user.id !== "412611450364887048") {
```
Comment (nhcarrigan) [inline src/modules/subcommands/handleBreakout.ts:24]:
```suggestion
  if (!(interaction.member as GuildMember)?.permissions.has("MOVE_MEMBERS")) {
```

This would confirm that the member using it has the correct permissions (i.e. our moderation team)

File: src/modules/subcommands/handleBreakout.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /* eslint-disable jsdoc/require-param */
-import { GuildChannel, VoiceChannel } from "discord.js";
+import { VoiceChannel } from "discord.js";
```
Comment (nhcarrigan) [inline src/modules/subcommands/handleBreakout.ts:2]:
```suggestion
import { GuildMember, VoiceChannel } from "discord.js";
```
Only if the suggestion on line 24 is accepted.

File: src/modules/subcommands/handleBreakout.ts [hunk 3]
```diff
@@ -12,6 +12,7 @@ export const handleBreakout: CommandHandler = async (bot, interaction) => {
   const channel = interaction.options.getChannel("channel", true);
   const duration = interaction.options.getInteger("duration", true);
   const size = interaction.options.getInteger("size", true);
+  const excludeUsers = ["840524820747911169"]; // exclude Sara
```
Comment (nhcarrigan) [inline src/modules/subcommands/handleBreakout.ts:15]:
```suggestion
  const excludeUsers = ["840524820747911169"]; // exclude Sara
```
If we intend to exclude specific users, we should move this out into a config I think.

File: src/commands/bot.ts [hunk 4]
```diff
@@ -9,7 +9,7 @@ import { handlePing } from "../modules/subcommands/handlePing";
 
 export const bot: Command = {
   data: new SlashCommandBuilder()
-    .setName("bot")
+    .setName("eddiebot-breakout-status")
```
Comment (nhcarrigan) [inline src/commands/bot.ts:12]: I'm curious why the command name changes.

**Review by nhcarrigan — CHANGES_REQUESTED** [review]
Some thoughts. Let me know how you feel about them.

File: src/modules/subcommands/handleBreakout.ts (hunk 3 above)
Comment (nhcarrigan) [reply src/modules/subcommands/handleBreakout.ts:15]: I changed my mind on this. I think we should not be doing any config for ignoring users. Will open up an issue instead.

File: src/modules/subcommands/handleBreakout.ts [hunk 5]
```diff
@@ -40,17 +51,33 @@ export const handleBreakout: CommandHandler = async (bot, interaction) => {
...
     }
   }
 
+  try {
+    mutableMembers.forEach(
+      async (m) => await m.voice.setChannel(newChannels[0])
+    );
+  } catch (e) {
+    console.log(e);
+  }
```
Comment (nhcarrigan) [inline src/modules/subcommands/handleBreakout.ts:68]:
```suggestion
  mutableMembers.forEach(async (m) => {
    try {
      await m.voice.setChannel(newChannels[0]);
    } catch (e) {
      console.log(e);
    }
  });
```

@eddiejaoude I'm assuming this branch is deployed...

The issue with #22 is because the error comes from within the `.forEach` callback which isn't passed up to the try/catch, I believe.

File: src/modules/subcommands/handleBreakout.ts (hunk 1 above)
Comment (eddiejaoude) [reply src/modules/subcommands/handleBreakout.ts:24]: nice!!

File: src/modules/subcommands/handleBreakout.ts (hunk 3 above)
Comment (eddiejaoude) [reply src/modules/subcommands/handleBreakout.ts:15]: I think this could be part of the command 👍  in a new issue

File: src/commands/bot.ts (hunk 4 above)
Comment (eddiejaoude) [reply src/commands/bot.ts:12]: `bot` seemed to generic

File: src/modules/subcommands/handleBreakout.ts (hunk 5 above)
Comment (eddiejaoude) [reply src/modules/subcommands/handleBreakout.ts:68]: Ah good spot 👍

File: src/modules/subcommands/handleBreakout.ts (hunk 2 above)
Comment (eddiejaoude) [reply src/modules/subcommands/handleBreakout.ts:2]: I could not see that suggestion? Maybe I am just tired 🤦‍♂️

Comment (nhcarrigan) [reply src/modules/subcommands/handleBreakout.ts:2]: You committed it 🙂

File: src/commands/bot.ts (hunk 4 above)
Comment (nhcarrigan) [reply src/commands/bot.ts:12]: IMHO, the command names *should* be generic (these are what the user has to type).

The description is where extra information can be displayed.

File: src/modules/subcommands/handleBreakout.ts (hunk 2 above)
Comment (eddiejaoude) [reply src/modules/subcommands/handleBreakout.ts:2]: ok 😂

File: src/commands/bot.ts (hunk 4 above)
Comment (eddiejaoude) [reply src/commands/bot.ts:12]: Ok may be `network` would be better
